name: palestine_trusted_device
description: Check if the device is trustworthy, rooted, jailbroken, developer mode is on, ...etc.
version: 0.0.1

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: net.msayed.palestine_trusted_device
        pluginClass: PalestineTrustedDevicePlugin
      ios:
        pluginClass: PalestineTrustedDevicePlugin
