name: palestine_connection
description: Lightweight internet connection test, lookup Google domain.
version: 0.0.11

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
