name: palestine_connection
description: Simple internet connection checker, Try to lookup Google base domain.
version: 0.0.9

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
